name: Run E2E Application and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run : |
        sh ./scripts/run.sh
    - name: Publish Test Reports
      uses: actions/upload-artifact@v2
      with:
        name: SeleniumAssets
        path: ./reports
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
