name: Run E2E Application and Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run : |
        sh ./scripts/run.sh
    - name: Copy report and videos
      env:
        REPORT_DIRECTORY: /assets
      run: |
        cp -r 

